/**
 * CNR KB migration: legacy Laravel Blade (HTML) -> Starlight Markdown.
 *
 * POC scope: migrates the editorial content sections listed in INCLUDE.
 * Skips the 1298 data-driven TLD pages (domains/tlds) — those are a
 * phase-2, generated-from-data concern.
 *
 * Usage: node scripts/migrate.mjs /path/to/gcus-cnr-kb-static
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, relative, basename, posix } from 'node:path';
import * as cheerio from 'cheerio';
import TurndownService from 'turndown';
import { gfm } from 'turndown-plugin-gfm';

const SRC_REPO = process.argv[2];
if (!SRC_REPO) {
  console.error('Pass the path to the legacy repo as arg 1.');
  process.exit(1);
}
const KB_ROOT = join(SRC_REPO, 'resources/views/cnr/kb');
const OUT_ROOT = join(process.cwd(), 'src/content/docs');

// Sections to migrate for the POC. Everything else (esp. domains/tlds) skipped.
const INCLUDE = ['help', 'dns', 'ssl', 'services', 'domains', 'api'];
// Within domains, skip the mass TLD pages.
const SKIP_DIRS = ['domains/tlds'];

// Any host serving the legacy KB — used as the fallback target for links to
// pages we did NOT migrate (so there are no dead internal links in the POC).
const LEGACY_ORIGIN = 'https://kb.centralnicreseller.com';

// old-URL-path -> new-slug, populated before conversion (see run section).
let LINK_MAP = new Map();

const td = new TurndownService({
  headingStyle: 'atx',
  codeBlockStyle: 'fenced',
  bulletListMarker: '-',
});
// GFM plugin: converts <table> to Markdown pipe tables, plus strikethrough etc.
// (Header promotion for header-less legacy tables is done in cheerio, below.)
td.use(gfm);
td.addRule('stripAnchors', {
  filter: (node) => node.nodeName === 'A' && !node.getAttribute('href'),
  replacement: (content) => content,
});

function listBladeFiles(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) out.push(...listBladeFiles(full));
    else if (entry.endsWith('.blade.php')) out.push(full);
  }
  return out;
}

/** Decode HTML entities (&quot; &amp; &#039; …) to their real characters. */
function decodeEntities(s) {
  if (!s || !s.includes('&')) return s;
  return cheerio.load(`<x>${s}</x>`)('x').text();
}

function extractParam(header, key) {
  const re = new RegExp(`'${key}'\\s*=>\\s*'((?:[^'\\\\]|\\\\.)*)'`);
  const m = header.match(re);
  return m ? decodeEntities(m[1].replace(/\\'/g, "'")).trim() : '';
}

function frontmatterEscape(s) {
  return '"' + String(s).replace(/"/g, '\\"') + '"';
}

/** Map legacy blade path -> Starlight markdown output path. */
function outPathFor(bladePath) {
  let rel = relative(KB_ROOT, bladePath).replace(/\.blade\.php$/, '');
  // A section landing file (e.g. "help") becomes "help/index" so the
  // autogenerated sidebar directory has a proper index page.
  const segs = rel.split('/');
  const dirExistsForLeaf = (() => {
    try {
      return statSync(join(KB_ROOT, rel)).isDirectory();
    } catch {
      return false;
    }
  })();
  if (dirExistsForLeaf) rel = rel + '/index';
  return join(OUT_ROOT, rel + '.md');
}

/** Legacy URL path a blade file was served at, e.g. '/api/api-command/AddCertificate'. */
function oldPathFor(bladePath) {
  return '/' + relative(KB_ROOT, bladePath).replace(/\.blade\.php$/, '');
}

/**
 * New Starlight route slug for a blade file, e.g. 'api/api-command/addcertificate'.
 * Astro lowercases route slugs, so we lowercase here too — otherwise links keep
 * the original file casing and 404 on case-sensitive hosts (GitHub Pages). '' = home.
 */
function slugFor(bladePath) {
  return relative(OUT_ROOT, outPathFor(bladePath))
    .replace(/\.md$/, '')
    .replace(/\/index$/, '')
    .replace(/^index$/, '')
    .toLowerCase();
}

/**
 * Resolve a legacy href against the current page and rewrite it:
 *  - migrated target -> a correct RELATIVE link to the new route (base-independent)
 *  - un-migrated internal target -> absolute link to the legacy origin (no dead links)
 *  - external / mailto / same-page anchor -> left as-is
 */
function resolveLink(pageOld, pageSlug, href) {
  if (!href) return href;
  if (/^(https?:|mailto:|tel:|data:)/i.test(href)) return href;
  if (href.startsWith('#')) return href; // same-page anchor

  const hashIdx = href.indexOf('#');
  const frag = hashIdx >= 0 ? href.slice(hashIdx) : '';
  let pathPart = (hashIdx >= 0 ? href.slice(0, hashIdx) : href).split('?')[0];
  pathPart = pathPart.replace(/index\.html$/i, '').replace(/\.html$/i, '');

  // Absolute legacy path this link points to.
  let abs = pathPart.startsWith('/')
    ? posix.normalize(pathPart)
    : posix.normalize(posix.join(posix.dirname(pageOld), pathPart || '.'));
  abs = abs.replace(/\/+$/, '') || '/';

  const candidates = [abs];
  if (abs.endsWith('/index')) candidates.push(abs.replace(/\/index$/, ''));
  if (abs === '/') candidates.push('/index');

  for (const c of candidates) {
    if (LINK_MAP.has(c)) {
      const targetSlug = LINK_MAP.get(c);
      let rel = posix.relative('/' + pageSlug, '/' + targetSlug);
      if (rel === '') rel = '.';
      return rel.replace(/\/?$/, '/') + frag; // trailing slash for Starlight routes
    }
  }
  // Not migrated -> keep it working by pointing at the legacy origin.
  return LEGACY_ORIGIN + abs + frag;
}

function convert(bladePath) {
  const pageOld = oldPathFor(bladePath);
  const pageSlug = slugFor(bladePath);
  const raw = readFileSync(bladePath, 'utf8');

  // Header of the @extends(...) call holds the meta.
  const header = raw.slice(0, raw.indexOf('@section') === -1 ? 400 : raw.indexOf('@section'));
  let title = extractParam(header, 'documentTitle');
  const description = extractParam(header, 'metaDescription');
  title = title
    .replace(/\s*[-–|]\s*CentralNic Reseller Knowledge Base\s*$/i, '')
    .replace(/\s*[-–|]\s*CentralNic Reseller\s*$/i, '')
    .replace(/\s*[-–|]\s*(API|EPP)\s+Command\s*$/i, '') // "AddCertificate - API Command"
    .replace(/\s{2,}/g, ' ')
    .trim();

  // Content section.
  const secStart = raw.indexOf("@section('content')");
  if (secStart === -1) return null;
  let body = raw.slice(secStart + "@section('content')".length);
  body = body.replace(/@endsection[\s\S]*$|@stop[\s\S]*$/, '');

  // Drop blade directives / comments / components we can't render without Laravel.
  body = body
    .replace(/\{\{--[\s\S]*?--\}\}/g, '') // {{-- blade comments --}}
    .replace(/@php[\s\S]*?@endphp/g, '')
    .replace(/@(include|extends|section|endsection|stop|yield|component|endcomponent|slot|endslot|if|elseif|else|endif|foreach|endforeach|for|endfor|isset|endisset)\b[^\n]*/g, '')
    .replace(/\{\{[^}]*\}\}/g, '') // {{ $echo }} expressions
    .replace(/<\/?x-[^>]*>/g, '');

  const $ = cheerio.load(body, null, false);
  // Remove repeated page furniture.
  $('.breadcrumb, aside, .box.help, nav, .rel_nav').remove();
  // Prefer the main content column if present.
  let scope = $('.main').first();
  if (!scope.length) scope = $.root();
  // Drop leftover empty anchor spans.
  scope.find('span.anchor').remove();

  // Normalise tables so the GFM plugin emits proper Markdown tables:
  //  - unwrap <span> inside cells (turndown keeps them otherwise)
  //  - if a table has no <th>, promote its first row's <td> cells to <th>
  scope.find('table').each((_, table) => {
    const $t = $(table);
    $t.find('td span, th span').each((_, s) => $(s).replaceWith($(s).html() || ''));
    if ($t.find('th').length === 0) {
      const firstRow = $t.find('tr').first();
      firstRow.find('td').each((_, td) => {
        const $td = $(td);
        const th = $('<th>').html($td.html() || '');
        $td.replaceWith(th);
      });
    }
  });

  // Rewrite internal links (map-based; falls back to the legacy origin).
  scope.find('a[href]').each((_, el) => {
    $(el).attr('href', resolveLink(pageOld, pageSlug, $(el).attr('href')));
  });

  // Rewrite image sources to root-absolute public paths; drop unknown ones.
  // Legacy assets live under public/{imagetypes,images,dist/img} on the old site.
  scope.find('img[src]').each((_, el) => {
    const src = $(el).attr('src') || '';
    if (/^https?:/i.test(src)) return;
    const m = src.match(/(imagetypes\/|images\/|dist\/img\/)(.*)$/);
    if (m) {
      // Point at the existing live KB so assets are path-independent
      // (works under a GitHub Pages sub-path). Phase 2: self-host these.
      $(el).attr('src', 'https://kb.centralnicreseller.com/' + m[1] + m[2]);
      $(el).removeAttr('srcset');
      $(el).removeAttr('width');
      $(el).removeAttr('height');
    } else {
      $(el).remove();
    }
  });

  // Overview/teaser pages: turn the ".box" link cards into Starlight <LinkCard>s.
  // (Links inside were already rewritten by the loop above.)
  const cards = [];
  scope.find('.box').each((_, box) => {
    const $box = $(box);
    const a = $box.find('a[href]').first();
    if (!a.length) return;
    const href = a.attr('href');
    const cardTitle = ($box.find('h2, h3, h4').first().text() || a.attr('title') || '').trim();
    const cardDesc = $box.find('em').first().text().trim();
    if (href && cardTitle) cards.push({ href, title: cardTitle, description: cardDesc });
  });
  // Drop the teaser containers so turndown doesn't mangle them into text soup.
  scope.find('.teaser, .boxes').remove();
  scope.find('.box').remove();

  // Remove the first <h1> (Starlight renders the frontmatter title as h1).
  const firstH1 = scope.find('h1').first();
  const h1Text = firstH1.text().trim();
  firstH1.remove();
  if (!title && h1Text) title = h1Text;

  const html = scope.html() || '';
  let md = td.turndown(html).trim();
  // Collapse excessive blank lines.
  md = md.replace(/\n{3,}/g, '\n\n');

  if (!title) title = basename(bladePath).replace(/\.blade\.php$/, '').replace(/[-_]/g, ' ');

  const fm =
    [
      '---',
      `title: ${frontmatterEscape(title)}`,
      description ? `description: ${frontmatterEscape(description.slice(0, 160))}` : null,
      '---',
    ]
      .filter(Boolean)
      .join('\n') + '\n\n';

  // Build the file. Pages with link cards become .mdx (need components).
  if (cards.length) {
    const grid =
      '<CardGrid>\n' +
      cards
        .map(
          (c) =>
            `  <LinkCard title={${JSON.stringify(c.title)}} href={${JSON.stringify(c.href)}}` +
            (c.description ? ` description={${JSON.stringify(c.description)}}` : '') +
            ` />`
        )
        .join('\n') +
      '\n</CardGrid>';
    const imp = "import { CardGrid, LinkCard } from '@astrojs/starlight/components';\n\n";
    const content = fm + imp + (md ? md + '\n\n' : '') + grid + '\n';
    return { content, ext: '.mdx' };
  }

  return { content: fm + md + '\n', ext: '.md' };
}

// --- run ---
let written = 0,
  skipped = 0,
  empty = 0;
const sections = INCLUDE.filter((s) => {
  try {
    return statSync(join(KB_ROOT, s)).isDirectory() || statSync(join(KB_ROOT, s + '.blade.php')).isFile();
  } catch {
    return false;
  }
});

const files = [];
for (const s of sections) {
  // section landing file
  const landing = join(KB_ROOT, s + '.blade.php');
  try {
    if (statSync(landing).isFile()) files.push(landing);
  } catch {}
  // section directory
  try {
    if (statSync(join(KB_ROOT, s)).isDirectory()) files.push(...listBladeFiles(join(KB_ROOT, s)));
  } catch {}
}

// Files we will actually migrate (after SKIP filtering).
const toMigrate = files.filter((f) => {
  const rel = relative(KB_ROOT, f);
  return !SKIP_DIRS.some((d) => rel.startsWith(d + '/'));
});
skipped += files.length - toMigrate.length;

// Build the link map BEFORE converting, so links can resolve to real targets.
LINK_MAP = new Map();
for (const f of toMigrate) LINK_MAP.set(oldPathFor(f), slugFor(f));
LINK_MAP.set('/index', ''); // homepage
LINK_MAP.set('/', '');

for (const f of toMigrate) {
  const result = convert(f);
  if (!result) {
    skipped++;
    continue;
  }
  if (result.content.replace(/---[\s\S]*?---/, '').trim().length < 8) empty++;
  const outPath = outPathFor(f).replace(/\.md$/, result.ext);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, result.content, 'utf8');
  written++;
}

console.log(`Migrated: ${written} pages | skipped: ${skipped} | near-empty: ${empty}`);
console.log(`Output -> ${OUT_ROOT}`);
