/**
 * CNR KB migration: legacy Laravel Blade (HTML) -> Starlight Markdown.
 *
 * POC scope: migrates the editorial content sections listed in INCLUDE.
 * Skips the 1298 data-driven TLD pages (domains/tlds) — those are a
 * phase-2, generated-from-data concern.
 *
 * Usage: node scripts/migrate.mjs /path/to/gcus-cnr-kb-static
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, relative, basename } from 'node:path';
import * as cheerio from 'cheerio';
import TurndownService from 'turndown';

const SRC_REPO = process.argv[2];
if (!SRC_REPO) {
  console.error('Pass the path to the legacy repo as arg 1.');
  process.exit(1);
}
const KB_ROOT = join(SRC_REPO, 'resources/views/cnr/kb');
const OUT_ROOT = join(process.cwd(), 'src/content/docs');

// Sections to migrate for the POC. Everything else (esp. domains/tlds) skipped.
const INCLUDE = ['help', 'dns', 'ssl', 'services', 'domains'];
// Within domains, skip the mass TLD pages.
const SKIP_DIRS = ['domains/tlds'];

const td = new TurndownService({
  headingStyle: 'atx',
  codeBlockStyle: 'fenced',
  bulletListMarker: '-',
});
// Keep tables readable (turndown drops them by default without a plugin;
// convert simple tables to GFM manually).
td.addRule('stripAnchors', {
  filter: (node) => node.nodeName === 'A' && !node.getAttribute('href'),
  replacement: (content) => content,
});

function listBladeFiles(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) out.push(...listBladeFiles(full));
    else if (entry.endsWith('.blade.php')) out.push(full);
  }
  return out;
}

function extractParam(header, key) {
  const re = new RegExp(`'${key}'\\s*=>\\s*'((?:[^'\\\\]|\\\\.)*)'`);
  const m = header.match(re);
  return m ? m[1].replace(/\\'/g, "'").trim() : '';
}

function frontmatterEscape(s) {
  return '"' + String(s).replace(/"/g, '\\"') + '"';
}

/** Map legacy blade path -> Starlight markdown output path. */
function outPathFor(bladePath) {
  let rel = relative(KB_ROOT, bladePath).replace(/\.blade\.php$/, '');
  // A section landing file (e.g. "help") becomes "help/index" so the
  // autogenerated sidebar directory has a proper index page.
  const segs = rel.split('/');
  const dirExistsForLeaf = (() => {
    try {
      return statSync(join(KB_ROOT, rel)).isDirectory();
    } catch {
      return false;
    }
  })();
  if (dirExistsForLeaf) rel = rel + '/index';
  return join(OUT_ROOT, rel + '.md');
}

function rewriteLink(href) {
  if (!href) return href;
  if (/^(https?:|mailto:|tel:|#)/i.test(href)) return href;
  // strip .html, index.html -> ./
  let h = href.replace(/index\.html$/i, '').replace(/\.html(#.*)?$/i, '$1');
  return h;
}

function convert(bladePath) {
  const raw = readFileSync(bladePath, 'utf8');

  // Header of the @extends(...) call holds the meta.
  const header = raw.slice(0, raw.indexOf('@section') === -1 ? 400 : raw.indexOf('@section'));
  let title = extractParam(header, 'documentTitle');
  const description = extractParam(header, 'metaDescription');
  title = title.replace(/\s*[-–]\s*CentralNic Reseller Knowledge Base\s*$/i, '').trim();

  // Content section.
  const secStart = raw.indexOf("@section('content')");
  if (secStart === -1) return null;
  let body = raw.slice(secStart + "@section('content')".length);
  body = body.replace(/@endsection[\s\S]*$|@stop[\s\S]*$/, '');

  // Drop blade directives / components we can't render without Laravel.
  body = body
    .replace(/@php[\s\S]*?@endphp/g, '')
    .replace(/@(include|extends|section|endsection|stop|yield|component|endcomponent|slot|endslot|if|elseif|else|endif|foreach|endforeach|for|endfor|isset|endisset)\b[^\n]*/g, '')
    .replace(/<\/?x-[^>]*>/g, '');

  const $ = cheerio.load(body, null, false);
  // Remove repeated page furniture.
  $('.breadcrumb, aside, .box.help, nav').remove();
  // Prefer the main content column if present.
  let scope = $('.main').first();
  if (!scope.length) scope = $.root();
  // Drop leftover empty anchor spans.
  scope.find('span.anchor').remove();

  // Rewrite internal links.
  scope.find('a[href]').each((_, el) => {
    $(el).attr('href', rewriteLink($(el).attr('href')));
  });

  // Rewrite image sources to root-absolute public paths; drop unknown ones.
  // Legacy assets live under public/{imagetypes,images,dist/img} on the old site.
  scope.find('img[src]').each((_, el) => {
    const src = $(el).attr('src') || '';
    if (/^https?:/i.test(src)) return;
    const m = src.match(/(imagetypes\/|images\/|dist\/img\/)(.*)$/);
    if (m) {
      // Point at the existing live KB so assets are path-independent
      // (works under a GitHub Pages sub-path). Phase 2: self-host these.
      $(el).attr('src', 'https://kb.centralnicreseller.com/' + m[1] + m[2]);
      $(el).removeAttr('srcset');
      $(el).removeAttr('width');
      $(el).removeAttr('height');
    } else {
      $(el).remove();
    }
  });

  // Remove the first <h1> (Starlight renders the frontmatter title as h1).
  const firstH1 = scope.find('h1').first();
  const h1Text = firstH1.text().trim();
  firstH1.remove();
  if (!title && h1Text) title = h1Text;

  const html = scope.html() || '';
  let md = td.turndown(html).trim();
  // Collapse excessive blank lines.
  md = md.replace(/\n{3,}/g, '\n\n');

  if (!title) title = basename(bladePath).replace(/\.blade\.php$/, '').replace(/[-_]/g, ' ');

  const fm =
    [
      '---',
      `title: ${frontmatterEscape(title)}`,
      description ? `description: ${frontmatterEscape(description.slice(0, 160))}` : null,
      '---',
    ]
      .filter(Boolean)
      .join('\n') + '\n\n';

  return { fm, md };
}

// --- run ---
let written = 0,
  skipped = 0,
  empty = 0;
const sections = INCLUDE.filter((s) => {
  try {
    return statSync(join(KB_ROOT, s)).isDirectory() || statSync(join(KB_ROOT, s + '.blade.php')).isFile();
  } catch {
    return false;
  }
});

const files = [];
for (const s of sections) {
  // section landing file
  const landing = join(KB_ROOT, s + '.blade.php');
  try {
    if (statSync(landing).isFile()) files.push(landing);
  } catch {}
  // section directory
  try {
    if (statSync(join(KB_ROOT, s)).isDirectory()) files.push(...listBladeFiles(join(KB_ROOT, s)));
  } catch {}
}

for (const f of files) {
  const rel = relative(KB_ROOT, f);
  if (SKIP_DIRS.some((d) => rel.startsWith(d + '/'))) {
    skipped++;
    continue;
  }
  const result = convert(f);
  if (!result) {
    skipped++;
    continue;
  }
  if (!result.md || result.md.length < 8) {
    empty++;
    // still write a stub so nav is complete
  }
  const outPath = outPathFor(f);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, result.fm + result.md + '\n', 'utf8');
  written++;
}

console.log(`Migrated: ${written} pages | skipped: ${skipped} | near-empty: ${empty}`);
console.log(`Output -> ${OUT_ROOT}`);
